language: cpp

script:
# - wget https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz
# - tar -xf cmake-3.5.2-Linux-x86_64.tar.gz
 - mkdir build
 - cd build
# - ../cmake-3.5.2-Linux-x86_64/bin/cmake .. -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER
 - cmake .. -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER
 - cmake --build .
 - ctest --output-on-failure
 
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="C_COMPILER=gcc-7 && CXX_COMPILER=g++-7"
    - os: osx
      osx_image: xcode9.2
      env:
        - MATRIX_EVAL="C_COMPILER=clang && CXX_COMPILER=clang++"
    - os: windows
      env:
        - MATRIX_EVAL="C_COMPILER=cl && CXX_COMPILER=cl"

before_install:
    - eval "${MATRIX_EVAL}"
